In [1]:
from pandas import Series,DataFrame
import pandas as pd


In [2]:
obj = Series([4,7,-5,3])

In [3]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3])

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj1 = Series([1,4,67,-1],index=['a','b','v','d'])

In [7]:
obj1

a     1
b     4
v    67
d    -1
dtype: int64

In [8]:
obj1['v']

67

In [9]:
obj1['d'] = 44

In [10]:
obj1

a     1
b     4
v    67
d    44
dtype: int64

In [11]:
obj1[obj1>1]

b     4
v    67
d    44
dtype: int64

In [12]:
obj1*2

a      2
b      8
v    134
d     88
dtype: int64

In [13]:
obj1**2

a       1
b      16
v    4489
d    1936
dtype: int64

In [14]:
np

NameError: name 'np' is not defined

In [ ]:
'b' in obj1

In [15]:
67 in obj1

False

In [16]:
import numpy as np

In [17]:
sdata = {'Ohio':35000,'Texas':710000,'Oregon':16000,'Uath':5000}

In [18]:
obj2 = Series(sdata)

In [19]:
obj2

Ohio       35000
Oregon     16000
Texas     710000
Uath        5000
dtype: int64

In [20]:
states = ['Cal','Ohio','Oregon','Texas']

In [21]:
obj3 = Series(sdata,index=states)

In [22]:
obj3

Cal            NaN
Ohio       35000.0
Oregon     16000.0
Texas     710000.0
dtype: float64

In [23]:
pd.notnull(obj3)

Cal       False
Ohio       True
Oregon     True
Texas      True
dtype: bool

In [24]:
obj2+obj3

Cal             NaN
Ohio        70000.0
Oregon      32000.0
Texas     1420000.0
Uath            NaN
dtype: float64

In [25]:
obj2.name

In [26]:
obj3

Cal            NaN
Ohio       35000.0
Oregon     16000.0
Texas     710000.0
dtype: float64

In [27]:
obj3.name = 'population'

In [28]:
obj3.index.name = 'state'

In [29]:
obj3

state
Cal            NaN
Ohio       35000.0
Oregon     16000.0
Texas     710000.0
Name: population, dtype: float64

In [30]:
obj1

a     1
b     4
v    67
d    44
dtype: int64

In [31]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada'],'year':[2000,2001,2002,2001,2002],'pop':[1.2,1.6,1.3,1.4,1.6]}

In [32]:
frame = DataFrame(data)

In [33]:
frame

pop   state  year
0  1.2    Ohio  2000
1  1.6    Ohio  2001
2  1.3    Ohio  2002
3  1.4  Nevada  2001
4  1.6  Nevada  2002

In [34]:
DataFrame(data,columns = ['state','year','pop'])

state  year  pop
0    Ohio  2000  1.2
1    Ohio  2001  1.6
2    Ohio  2002  1.3
3  Nevada  2001  1.4
4  Nevada  2002  1.6

In [35]:
frame2 = DataFrame(data, columns=['state','year','pop','debt'], index=['one','two','three','four','five'])

In [36]:
frame2

state  year  pop debt
one      Ohio  2000  1.2  NaN
two      Ohio  2001  1.6  NaN
three    Ohio  2002  1.3  NaN
four   Nevada  2001  1.4  NaN
five   Nevada  2002  1.6  NaN

In [37]:
frame2.columns

Index(['state', 'year', 'pop', 'debt'], dtype='object')

In [38]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [39]:
frame2.pop

<bound method NDFrame.pop of         state  year  pop debt
one      Ohio  2000  1.2  NaN
two      Ohio  2001  1.6  NaN
three    Ohio  2002  1.3  NaN
four   Nevada  2001  1.4  NaN
five   Nevada  2002  1.6  NaN>

In [40]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [41]:
frame2.ix['one']

/Users/duli/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


state    Ohio
year     2000
pop       1.2
debt      NaN
Name: one, dtype: object

In [42]:
frame2

state  year  pop debt
one      Ohio  2000  1.2  NaN
two      Ohio  2001  1.6  NaN
three    Ohio  2002  1.3  NaN
four   Nevada  2001  1.4  NaN
five   Nevada  2002  1.6  NaN

In [43]:
frame2['debt'] = 22

In [44]:
frame2

state  year  pop  debt
one      Ohio  2000  1.2    22
two      Ohio  2001  1.6    22
three    Ohio  2002  1.3    22
four   Nevada  2001  1.4    22
five   Nevada  2002  1.6    22

In [45]:
frame2['debt'] = np.arange(5.)

In [46]:
np.arange(5.)

array([0., 1., 2., 3., 4.])

In [47]:
frame2

state  year  pop  debt
one      Ohio  2000  1.2   0.0
two      Ohio  2001  1.6   1.0
three    Ohio  2002  1.3   2.0
four   Nevada  2001  1.4   3.0
five   Nevada  2002  1.6   4.0

In [48]:
val = Series([-1.2,-1.5,-1.7],index=['two','four','five'])

In [49]:
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [50]:
frame2

state  year  pop  debt
one      Ohio  2000  1.2   0.0
two      Ohio  2001  1.6   1.0
three    Ohio  2002  1.3   2.0
four   Nevada  2001  1.4   3.0
five   Nevada  2002  1.6   4.0

In [51]:
frame2['debt']=val

In [52]:
frame2

state  year  pop  debt
one      Ohio  2000  1.2   NaN
two      Ohio  2001  1.6  -1.2
three    Ohio  2002  1.3   NaN
four   Nevada  2001  1.4  -1.5
five   Nevada  2002  1.6  -1.7

In [53]:
frame2['eastern'] = frame2.state == 'Ohio'

In [54]:
frame2

state  year  pop  debt  eastern
one      Ohio  2000  1.2   NaN     True
two      Ohio  2001  1.6  -1.2     True
three    Ohio  2002  1.3   NaN     True
four   Nevada  2001  1.4  -1.5    False
five   Nevada  2002  1.6  -1.7    False

In [55]:
pop = {'Nevada':{2001:2.4,2002:2.9},'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [56]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [57]:
frame3 = DataFrame(pop)

In [58]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [59]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [60]:
DataFrame(pop,index=[2000,2001,2002,2003])

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [61]:
pdata = {'Ohio':frame3['Ohio'][:-1],'Nevada':frame3['Nevada'][:2]}

In [62]:
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [63]:
frame3.index.name = 'year';frame3.columns.name = 'state'

In [64]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [65]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [66]:
frame2.values

array([['Ohio', 2000, 1.2, nan, True],
       ['Ohio', 2001, 1.6, -1.2, True],
       ['Ohio', 2002, 1.3, nan, True],
       ['Nevada', 2001, 1.4, -1.5, False],
       ['Nevada', 2002, 1.6, -1.7, False]], dtype=object)

In [67]:
obj = Series(range(3),index=['a','b','c'])

In [68]:
obj

a    0
b    1
c    2
dtype: int64

In [69]:
index= obj.index

In [70]:
index

Index(['a', 'b', 'c'], dtype='object')

In [71]:
index = pd.Index(np.arange(3))

In [72]:
index

Int64Index([0, 1, 2], dtype='int64')

In [73]:
obj2 = Series([2.3,-4.3,0],index = index)

In [74]:
obj2

0    2.3
1   -4.3
2    0.0
dtype: float64

In [75]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [76]:
'Ohio' in frame3.columns

True

In [77]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [78]:
obj = Series([4.5,-4.5,4.5,3.5],index=['d','b','a','c'])

In [79]:
obj

d    4.5
b   -4.5
a    4.5
c    3.5
dtype: float64

In [80]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [81]:
obj2

a    4.5
b   -4.5
c    3.5
d    4.5
e    NaN
dtype: float64

In [82]:
obj2 = obj.reindex(['a','b','c','d','e'],fill_value = 0)

In [83]:
obj2

a    4.5
b   -4.5
c    3.5
d    4.5
e    0.0
dtype: float64

In [84]:
obj3

state
Cal            NaN
Ohio       35000.0
Oregon     16000.0
Texas     710000.0
Name: population, dtype: float64

In [85]:
obj3 = Series(['Blue','Purple','Yellow'],index = [0, 2, 4])

In [86]:
obj3

0      Blue
2    Purple
4    Yellow
dtype: object

In [89]:
obj3.reindex(range(6),method = 'ffill')

0      Blue
1      Blue
2    Purple
3    Purple
4    Yellow
5    Yellow
dtype: object

In [90]:
frame  =DataFrame(np.arange(9).reshape((3,3)),index = ['a','c','d'],columns=['Ohio','Texas','California'])

In [91]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [94]:
frame2 = frame.reindex(['a','b','c','d'])

In [95]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [96]:
states = ['Texas','Utah','California']

In [99]:
frame2.columns

Index(['Ohio', 'Texas', 'California'], dtype='object')

In [100]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [101]:
frame.ix[['a','b','c','d'],states]

/Users/duli/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [102]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [104]:
states

['Texas', 'Utah', 'California']

In [105]:
obj = Series(np.arange(5.0),index=['a','b','c','d','e'])

In [106]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [107]:
new_obj = obj.drop('c')

In [108]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [109]:
data = DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','New York'],columns=['one','two','three','four'])

In [110]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [112]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [116]:
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [117]:
data.drop(['two','four'],axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [118]:
obj = Series(np.arange(4.),index=['a','b','c','d'])

In [119]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [120]:
obj['b']

1.0

In [121]:
obj[1]

1.0

In [122]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [123]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [125]:
obj['b':'c']=5

In [126]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [127]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [128]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [129]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [130]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [131]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [133]:
data[data<5] = 0

In [134]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [135]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [136]:
data = DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','New York'],columns=['one','two','three','four'])

In [140]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int64

In [141]:
data.ix[['Colorado','Utah'],[3,0,1]]

four  one  two
Colorado     7    4    5
Utah        11    8    9

In [142]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [144]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [147]:
data.ix[data.three>5,:3]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [148]:
s1 = Series([7.1,-2.5,3.4,1.5],index=['a','c','d','e'])

In [149]:
s1

a    7.1
c   -2.5
d    3.4
e    1.5
dtype: float64

In [150]:
s2 = Series([-2.1,4.5,3,45,1.3],index=['a','c','e','f','g'])

In [151]:
s1+s2

a    5.0
c    2.0
d    NaN
e    4.5
f    NaN
g    NaN
dtype: float64